batchsize: 4
epoch: 100
official_data_path: "your_path/dataset/data"
data_path: "your_path/fundus&angio_dataset/data"
test_dir: "your_path/dataset/Dataset/ABNORMAL"
to_shuffle: True
use_separable: False
normal_vit: False